### ISSUE TITLE
Stripped Bamboo Sign crashes - 1.19 Beta 7 & 8

### ISSUE THREAD

**Issue by Fris44** [moddingplayground/twigs-fabric#21]
Game crashes when rendering in Stripped Bamboo Sign, both when trying to place it or if it's already placed and you're loading in the chunks on 1.19.
Tried with both beta 7 and beta 8.
Attached is crash log using beta 8

-----------------------------------

How to recreate:
1. Use Twigs 1.19 beta 7 or 8
2. Load up a world
3. Place down a sign
4. Crash

-----------------------------------

[crash-2022-08-19_01.38.35-client.txt](https://github.com/moddingplayground/twigs-fabric/files/9378274/crash-2022-08-19_01.38.35-client.txt)

**Comment by dvitski** [comment]
I've just released a beta 9 with official 1.19.2 support, could you try that out?
Frame API is also updated to 0.26

**Comment by Fris44** [comment]
Updated both Twigs and Frame API, still crashes. normal and crash log attached
[latest.log](https://github.com/moddingplayground/twigs-fabric/files/9387568/latest.log)
[crash-2022-08-20_17.25.00-client.txt](https://github.com/moddingplayground/twigs-fabric/files/9387569/crash-2022-08-20_17.25.00-client.txt)

**Comment by Fris44** [comment]
I disabled all unnecessary mods (Something I admittedly should've done before as it is standard bug testing, sorry for wasting your time), and it doesn't crash. I will check which mod is having issues, report it here, and see about opening an issue about it on that mod's page as well

**Comment by Fris44** [comment]
Looks like the offending mod is [Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage), I already opened a issue there (as Github so helpfully told us)

**Comment by ghost** [comment]
Please see this, not sure why this happens exactly but I don't think it's necessarily the fault of bad code but rather how fabric/quilt mods are written in general:
https://github.com/devs-immortal/Paradise-Lost/issues/587

**Comment by andantet** [comment]
.

**Comment by dvitski** [comment]
Is this still an issue?

**Comment by Fris44** [comment]
Yep, just tried with newest versions of Twigs (2.0.0 beta 9), Frame (0.26.1), Ellemes' Container Library (2.1.0 alpha 10) and Expanded Storage (8.1.0 alpha 2), and the game still crashes when rendering a bamboo sign

**Comment by RealityAnomaly** [comment]
@andantet See what paradise-lost did here https://github.com/devs-immortal/Paradise-Lost/commit/75f5dc2b1fb087a3bfd974236bbfd7a5b9ff05cc vs what you're doing in frame-fabric at https://github.com/moddingplayground/frame-fabric/blob/ea73347f7b36a691ebdddf22777f2d9fe28b205f/frame-woods-v0/src/main/java/net/moddingplayground/frame/api/woods/v0/FrameSignType.java

**Comment by RealityAnomaly** [comment]
opened a pull request which fixes the issue on the Frame library: https://github.com/moddingplayground/frame-fabric/pull/5
